### ISSUE TITLE
Log4shell and Cytoscape

### ISSUE THREAD

**Issue by AlexanderPico** [sysbiolux/IDARE#6]
In an effort to mitigate the log4shell vulnerability in the Cytoscape ecosystem, we have scanned all the apps in the Cytoscape App Store. Your IDARE app contains a reference to log4j-core-2.3.jar.

Please update your package and upload new versions to the App Store as soon as possible.
https://apps.cytoscape.org/apps/idare

**Comment by tpfau** [comment]
Thanks for the Info, I'm currently having a look into it, since IDARE itself does not directly use log4j, I assume that one (or more) of its dependencies do. I'm currently in the process of checking it.

**Comment by tpfau** [comment]
Both the github version and the appstore version are updated.
